### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by plandolt** [vagrant-php/ubuntu#1]
With a regular sf2 application i got the following nginx error:

```
[error] 822#0: *1 upstream sent too big header while reading response header from upstream, client: 172.28.128.1, server: , request: "GET /app_dev.php HTTP/1.1", upstream: "fastcgi://unix://tmp/php-server-socket:"
```

I had to modify the nginx.conf file to add the parameters from http://stackoverflow.com/questions/17708152/nginx-overwrites-general-symfony-errors-with-502-bad-gateway

You may add these parameters per default?

**Comment by dominikzogg** [comment]
@scuben done https://github.com/vagrant-php/ubuntu/commit/ad1b139c3ce9d7ee82b396f03d6c35d19cd07749

**Comment by dominikzogg** [comment]
@scuben would be cool, if you could test it and give some feedback, if this solves the problem.

**Comment by plandolt** [comment]
@dominikzogg works fine now
