### ISSUE TITLE
Disable php garbage collection

### ISSUE THREAD

**Issue by plandolt** [vagrant-php/ubuntu#10]
Problem is explained here: http://somethingemporium.com/2007/06/obscure-error-with-php5-on-debian-ubuntu-session-phpini-garbage

Basically around every 100 request you get an error because it tries to cleanup the sessions but it does not have the needed file permissions. ubuntu is handling it with /etc/cron.d/php by itself.

I'll try to submit a PR for that soon

**Comment by dominikzogg** [comment]
@scuben you suggest to add the following php.ini value?

```
session.gc_probability = 0
```

**Comment by plandolt** [comment]
yes

**Comment by dominikzogg** [comment]
https://github.com/vagrant-php/ubuntu/commit/28a4d273c4a3bab96e8bcf34e808fa68f01faba5
