### ISSUE TITLE
custom application

### ISSUE THREAD

**Issue by plandolt** [vagrant-php/ubuntu#16]
On a couple of projects i need to have custom settings for nginx and (as a bonus) bindmount.

To achieve that I add another ansible role (e.g. nginx-application-custom) with a customised nginx config file. In addition to that I need to add it in the playbook.yml and add a bindmount file (even if i have nothing for bindmount; it requires the file to be existing).

**Comment by dominikzogg** [comment]
@scuben do you have an idea for a generic solution on that? any yaml config which adds new roles, or something like that,

**Comment by plandolt** [comment]
@dominikzogg Sorry, no idea yet. Not sure if I have time in the near future to work on something like that.

**Comment by dominikzogg** [comment]
@scuben did https://github.com/vagrant-php/ubuntu/pull/68 solve this issue?

**Comment by plandolt** [comment]
Yes 👍
