### ISSUE TITLE
Adjust write permissions to allow composer to cache files

### ISSUE THREAD

**Issue by plandolt** [vagrant-php/ubuntu#20]
Adjust write permissions to allow composer to cache files.

```
vagrant $ composer.phar update --dry-run
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Cannot create cache directory /home/vagrant/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/vagrant/.composer/cache/files/, or directory is not writable. Proceeding without cache
```

**Comment by dominikzogg** [comment]
@scuben this means, that the user vagrant does not have the permission to write files in its own home dir?

**Comment by plandolt** [comment]
@dominikzogg Yes, i just tested it on a fresh box.

```
drwxr-xr-x 3 root    root    4096 Feb 29 11:59 .composer
```

**Comment by dominikzogg** [comment]
@scuben i ask me, why composer creates this directory as root, cause there where no setup changes, did you checked if composer itself got issues about this?

**Comment by plandolt** [comment]
@dominikzogg Ah I now know why. I used to do a selfupdate b4 using composer. But composer.phar is a root owned file.

```
-rwxr-xr-x 1 root root 1569458 Feb 29 11:56 /usr/local/bin/composer.phar
```

Given that i used sudo to update composer which results in the root owned cache dir.

**Comment by dominikzogg** [comment]
@scuben if composer change the permission of the cache dir while updateing its definitely a composer bug

**Comment by dominikzogg** [comment]
@scuben do you sill have cache problems?

**Comment by plandolt** [comment]
@dominikzogg nope, all fine with new boxes.

**Comment by dominikzogg** [comment]
@scuben thanks for the fast response
