### ISSUE TITLE
create tls ca and add it to php

### ISSUE THREAD

**Issue by plandolt** [vagrant-php/ubuntu#27]
I run into an issue having a tls socket connection within two sites in the same vagrant setup. to connect to it i created (https://datacenteroverlords.com/2012/03/01/creating-your-own-ssl-certificate-authority/) a ca and configured openssl.cafile to point to the ca cert.

**Comment by dominikzogg** [comment]
@scuben interesting idea. would be very cool if you would create a PR to replace my simple solution

**Comment by dominikzogg** [comment]
@scuben did https://github.com/vagrant-php/ubuntu/pull/65 fixed that issue?

**Comment by plandolt** [comment]
Not sure. But the need for that is not here at the moment. Let's close that issue and come back to it when there is a case.
