### ISSUE TITLE
Intelligent fallback for cpu and memory

### ISSUE THREAD

**Issue by plandolt** [vagrant-php/ubuntu#3]
I used to use the following script to determine the number of cpus and memory. This "could" be used as a fallback but is open for discussion.

```
# Give VM 1/4 system memory & access to all cpu cores on the host
if host =~ /darwin/
  cpus = `sysctl -n hw.ncpu`.to_i
  # sysctl returns Bytes and we need to convert to MB
  mem = `sysctl -n hw.memsize`.to_i / 1024 / 1024 / 4
elsif host =~ /linux/
  cpus = `nproc`.to_i
  # meminfo shows KB and we need to convert to MB
  mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024 / 4
else
  # sorry Windows folks, I can't help you
  cpus = 2
  mem = 1024
end
```

**Comment by dominikzogg** [comment]
@scuben i do not like such a logic, cause this will end in max 2 boxes runs at onces, cause memory use of host os and for example an ide

**Comment by plandolt** [comment]
Yes thats true for the memory part. For cpu I think that if not specified it should take 1 and if specified "all" it could use that script

**Comment by dominikzogg** [comment]
@scuben should work now

https://github.com/vagrant-php/ubuntu/commit/d9ed416be9b2e818589d8259106009bd8830d912
