### ISSUE TITLE
switch to bento/ubuntu-16.04

### ISSUE THREAD

**Issue by plandolt** [vagrant-php/ubuntu#34]
Due to the fact that box-cutter isnt serving its vms anymore the community is switching to https://app.vagrantup.com/bento/boxes/ubuntu-16.04. I think vagrent-php/ubuntu should do the same. In the same step one could make the box (config.vm.box) configurable.

**Comment by dominikzogg** [comment]
@scuben thanks for the input, i like to replace the basebox, but i am not sure if its a good idea to make the box configurable, cause probably not every ubuntu 16.04 box would work with the setup

**Comment by plandolt** [comment]
yes thats true. but switching is a need bc on fresh setups you get 403 trying to download the box-cutter box.

**Comment by dominikzogg** [comment]
@scuben i am testing the bento box and will commit it if its work

**Comment by dominikzogg** [comment]
@scuben https://github.com/vagrant-php/ubuntu/tree/original-ubuntu-box can be uses temporary

**Comment by dominikzogg** [comment]
but the official image supports only virtualbox

**Comment by plandolt** [comment]
@dominikzogg thanks for the info. We currently use the bento box for new setups and did not face any problems so far.

**Comment by dominikzogg** [comment]
@scuben updated
