### ISSUE TITLE
installation of php-phpdbg forces php 7.3

### ISSUE THREAD

**Issue by plandolt** [vagrant-php/ubuntu#58]
Your newest commit to install php-phpdbg forces to install php 7.3. can you rollback that commit and use it in php.modules?

`
Start-Date: 2019-09-10  11:17:13
Commandline: /usr/bin/apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold install php-phpdbg
Requested-By: vagrant (1000)
Install: php7.3-readline:amd64 (7.3.9-1+ubuntu18.04.1+deb.sury.org+1, automatic), php7.3-json:amd64 (7.3.9-1+ubuntu18.04.1+deb.sury.org+1, automatic), php7.3-common:amd64 (7.3.9-1+ubuntu18.04.1+deb.sury.org+1, automatic), php7.3-opcache:amd64 (7.3.9-1+ubuntu18.04.1+deb.sury.org+1, automatic), php7.3-cli:amd64 (7.3.9-1+ubuntu18.04.1+deb.sury.org+1, automatic), php-phpdbg:amd64 (2:7.3+69+ubuntu18.04.1+deb.sury.org+2+php7.3), libpcre2-8-0:amd64 (10.33-1+ubuntu18.04.1+deb.sury.org+1, automatic), php7.3-phpdbg:amd64 (7.3.9-1+ubuntu18.04.1+deb.sury.org+1, automatic)
End-Date: 2019-09-10  11:17:24
`

ping @dominikzogg (just to be sure) :)

**Comment by dominikzogg** [comment]
@scuben very stange should work even with older php versions, could be i have to take the concrete ones instead of php-*, can you check if it would work with php7.x-phpdbg?

```
default /vagrant vagrant $ apt search phpdbg
Sortierung... Fertig
Volltextsuche... Fertig
php-phpdbg/bionic,bionic,now 2:7.3+69+ubuntu18.04.1+deb.sury.org+2+php7.3 all  [installiert]
  server-side, HTML-embedded scripting language (PHPDBG binary) (default)

php5.6-phpdbg/bionic 5.6.40-12+ubuntu18.04.1+deb.sury.org+1 amd64
  server-side, HTML-embedded scripting language (PHPDBG binary)

php7.0-phpdbg/bionic 7.0.33-11+ubuntu18.04.1+deb.sury.org+1 amd64
  server-side, HTML-embedded scripting language (PHPDBG binary)

php7.1-phpdbg/bionic 7.1.32-1+ubuntu18.04.1+deb.sury.org+1 amd64
  server-side, HTML-embedded scripting language (PHPDBG binary)

php7.2-phpdbg/bionic 7.2.22-1+ubuntu18.04.1+deb.sury.org+1 amd64
  server-side, HTML-embedded scripting language (PHPDBG binary)

php7.3-phpdbg/bionic,now 7.3.9-1+ubuntu18.04.1+deb.sury.org+1 amd64  [Installiert,automatisch]
  server-side, HTML-embedded scripting language (PHPDBG binary)

php7.4-phpdbg/bionic 7.4.0~beta4-2+ubuntu18.04.1+deb.sury.org+1 amd64
  server-side, HTML-embedded scripting language (PHPDBG binary)
```

**Comment by dominikzogg** [comment]
https://github.com/vagrant-php/ubuntu/commit/f5e5cfa054f984ee19aca3ce49c2faabc8ea961d

**Comment by plandolt** [comment]
it works with f5e5cfa

**Comment by dominikzogg** [comment]
@scuben thx for testing
