### ISSUE TITLE
drop: guest variable

### ISSUE THREAD

**Issue by dominikzogg** [vagrant-php/ubuntu#59]
hello @scuben i merged your PR to override the vagrant box. But if somebody tries to use it with an image that is not based on ubuntu it would not work, is it ok to drop the `guest` variable again?

https://github.com/vagrant-php/ubuntu/blob/18.04/vagrant-default.yml#L8

**Comment by plandolt** [comment]
Sure, sounds good

Von meinem iPhone gesendet
