### ISSUE TITLE
Remove xdebug from default installation

### ISSUE THREAD

**Issue by dominikzogg** [vagrant-php/ubuntu#71]
@scuben would you have an issue, when i would remove xdebug from the default installation (still installable over modules section in yaml)?

**Comment by bresam** [comment]
That's fine with me.

**Comment by dominikzogg** [comment]
@bresam would you prefer that xdebug config stays the same, and only the extension needed to be installed my additional modules or should i drop that part to?

**Comment by bresam** [comment]
@dominikzogg I personally would prefer when the configuration remains as implemented. But also looking forward to scubens response.

**Comment by plandolt** [comment]
I am fine with that but pls keep the default config part.

**Comment by dominikzogg** [comment]
https://github.com/vagrant-php/ubuntu/commit/a924264581a1f280accb397d48cac21e9b767f60
