### ISSUE TITLE
xdebug3

### ISSUE THREAD

**Issue by plandolt** [vagrant-php/ubuntu#76]
With xdebug3 there are some changes in variable names. Including on `xdebug.remote_autostart` and `xdebug.remote_enable`. Do you have any idea how to handle that? For me it's fine to just switch to the new variables. WDYT?

e.g. https://xdebug.org/docs/upgrade_guide#changed-xdebug.remote_autostart

**Comment by dominikzogg** [comment]
@scuben would love if you could test the change. Hopefully this will work with xdebug 2.x and 3.x

https://github.com/vagrant-php/ubuntu/pull/77
